# Generated by Django 6.0.5 on 2026-09-16 18:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import linkedin.intent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for the High-Intent Signal Layer. MUST be false by default.')),
                ('top_icp_enabled', models.BooleanField(default=False)),
                ('job_change_enabled', models.BooleanField(default=False)),
                ('funding_enabled', models.BooleanField(default=False)),
                ('engagement_enabled', models.BooleanField(default=False)),
                ('competitor_enabled', models.BooleanField(default=False)),
                ('influencer_enabled', models.BooleanField(default=False)),
                ('your_company_enabled', models.BooleanField(default=False)),
                ('job_change_keywords', models.JSONField(blank=True, default=list)),
                ('funding_keywords', models.JSONField(blank=True, default=list)),
                ('engagement_keywords', models.JSONField(blank=True, default=list)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_config', to='linkedin.campaign')),
            ],
            options={
                'verbose_name': 'Signal Configuration',
                'verbose_name_plural': 'Signal Configurations',
            },
        ),
        migrations.CreateModel(
            name='InfluencerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_targets', to='linkedin.signalconfiguration')),
            ],
            bases=(linkedin.intent.models.CanonicalLinkedInUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompetitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(max_length=500)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_targets', to='linkedin.signalconfiguration')),
            ],
            bases=(linkedin.intent.models.CanonicalLinkedInUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(max_length=500)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_targets', to='linkedin.signalconfiguration')),
            ],
            bases=(linkedin.intent.models.CanonicalLinkedInUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IntentSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('TOP_ICP', 'Top ICP'), ('JOB_CHANGE', 'Job Change'), ('FUNDING', 'Funding'), ('ENGAGEMENT', 'Content Engagement'), ('COMPETITOR', 'Competitor Engagement'), ('INFLUENCER', 'Influencer Engagement'), ('YOUR_COMPANY', 'Company Engagement')], max_length=50)),
                ('subject_id', models.CharField(help_text='Public identifier of the candidate profile. Must match LinkedInProfile.public_id', max_length=255)),
                ('source', models.CharField(help_text='Origin of the signal (e.g., specific competitor URL or query)', max_length=500)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Raw evidence data explaining why this signal was created (e.g. comment text, post URL)')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score from 0.0 to 1.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred in the real world (e.g. comment date)')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, help_text='When our system first discovered this signal')),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='When our system last updated this signal')),
                ('dedupe_key', models.CharField(help_text='Unique key to prevent duplicate signals for the exact same observation. Format: <subject_id>:<signal_type>:<evidence_hash>', max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_signals', to='linkedin.campaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'subject_id'], name='linkedin_in_campaig_79f5fc_idx'), models.Index(fields=['campaign', 'signal_type'], name='linkedin_in_campaig_bb2282_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'dedupe_key'), name='unique_signal_dedupe'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='confidence_range_check', violation_error_message='Confidence must be between 0.0 and 1.0')],
            },
        ),
    ]
