# Generated by Django 6.0.5 on 2026-06-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0008_add_siteconfig_active_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('engage', 'Feed Engagement')], max_length=20),
        ),
    ]
