# Generated by Django 6.0.5 on 2026-06-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0009_add_engage_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='like_daily_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('engage', 'Feed Engagement'), ('like', 'Like Profile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('like', 'Like')], max_length=20),
        ),
    ]
