# Generated by Django 6.0.5 on 2026-06-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0010_add_like_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='market_persona',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
