# Generated by Django 6.0.5 on 2026-06-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0011_add_campaign_market_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='active_end_hour',
            field=models.PositiveSmallIntegerField(default=23, help_text='Exclusive, 0-23 local time.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='active_start_hour',
            field=models.PositiveSmallIntegerField(default=6, help_text='Inclusive, 0-23 local time.'),
        ),
    ]
