# Generated by Django 6.0.5 on 2026-06-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0012_update_active_hours_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
