# Generated by Django 6.0.5 on 2026-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0013_add_task_failure_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Telegram bot token from @BotFather /newbot.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Your numeric chat ID (from @userinfobot) or @channelusername.', max_length=100),
        ),
    ]
