# Generated by manual edit — update active hours default to 4 PM–6 PM

from django.db import migrations, models


def update_existing_siteconfig(apps, schema_editor):
    SiteConfig = apps.get_model("linkedin", "SiteConfig")
    for cfg in SiteConfig.objects.all():
        changed = False
        if cfg.active_start_hour != 16:
            cfg.active_start_hour = 16
            changed = True
        if cfg.active_end_hour != 18:
            cfg.active_end_hour = 18
            changed = True
        if cfg.active_timezone != "Asia/Kolkata":
            cfg.active_timezone = "Asia/Kolkata"
            changed = True
        if changed:
            cfg.save()


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0014_siteconfig_telegram_bot_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="active_end_hour",
            field=models.PositiveSmallIntegerField(
                default=18, help_text="Exclusive, 0-23 local time."
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="active_start_hour",
            field=models.PositiveSmallIntegerField(
                default=16, help_text="Inclusive, 0-23 local time."
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="active_timezone",
            field=models.CharField(
                default="Asia/Kolkata",
                help_text="IANA timezone name (e.g. 'America/New_York').",
                max_length=64,
            ),
        ),
        migrations.RunPython(
            update_existing_siteconfig, reverse_code=migrations.RunPython.noop
        ),
    ]
