# Generated by Django 6.0.5 on 2026-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0016_siteconfig_work_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='enable_active_hours',
            field=models.BooleanField(default=True, help_text='Limit the daemon to a work shift per start; uncheck for 24/7.'),
        ),
    ]
