# Generated by Django 6.0.5 on 2026-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0017_alter_siteconfig_enable_active_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='search_geo_urn',
            field=models.CharField(blank=True, default='103544278,103644278,101165590,101174742,106442593,102454443', help_text='Comma-separated LinkedIn geo URNs scoping People search to those geographies (India=103544278, US=103644278, UK=101165590, Canada=101174742, UAE=106442593, Singapore=102454443). Empty = no geography filter.', max_length=256),
        ),
    ]
