# Generated by Django 6.0.5 on 2026-09-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0019_siteconfig_daemon_halt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_urn', models.CharField(max_length=200, unique=True)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('drafted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(max_length=500, unique=True)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Influencer',
                'verbose_name_plural': 'Influencers',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('like', 'Like'), ('draft_comments', 'Draft Comments')], max_length=20),
        ),
    ]
