# Generated by Django 6.0.5 on 2026-09-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0020_draftedcomment_influencer_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftedcomment',
            name='drafts_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='draftedcomment',
            name='post_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ai_persona_prompt',
            field=models.TextField(blank=True, default='You are an expert financial planner. Your goal is to react to LinkedIn posts with insightful, professional, and engaging comments that establish your authority and add value.', help_text='The system prompt instructing the LLM on its persona.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ai_tone_prompt',
            field=models.TextField(blank=True, default="Write exactly three distinct comments based on these three tones. Keep them max 3 sentences each:\n1. Polite: A standard, polished, and complimentary response.\n2. Contrarian: Politely challenging or offering an alternative perspective to spark debate.\n3. Cheerleading: Enthusiastic support and validation of the author's point or milestone.", help_text='The specific instructions for the 3 tones to generate.'),
        ),
    ]
