# Generated by Django 6.0.5 on 2026-09-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0021_draftedcomment_drafts_text_draftedcomment_post_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='engagement_group',
            field=models.CharField(choices=[('daily', 'Daily Posters'), ('regular', 'Regular Posters (Coupla times a week)'), ('rare', 'Rare Posters')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='ai_tone_prompt',
            field=models.TextField(blank=True, default="Write exactly three distinct comments based on these three tones. Keep them max 3 sentences each:\n1. Polite: A standard, polished, and complimentary response.\n2. Contrarian: Politely challenging or offering an alternative perspective to spark debate. DO NOT start with 'While I' or use repetitive opening phrases. Vary your approach significantly each time.\n3. Cheerleading: Enthusiastic support and validation of the author's point or milestone.", help_text='The specific instructions for the 3 tones to generate.'),
        ),
    ]
