# Generated by Django 6.0.5 on 2026-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0022_influencer_engagement_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='avg_comments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='follower_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='last_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
