# Generated by Django 6.0.5 on 2026-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0023_influencer_avg_comments_influencer_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='last_shift_completed_date',
            field=models.DateField(blank=True, help_text='Date when the daemon last completed a full shift.', null=True),
        ),
    ]
